package com.brady.goods.entity;

import java.io.Serializable;

public class Goods implements Serializable {
    private Integer id;

    private String goodsName;

    private Double price;

    private String goodsDesc;

    private Integer sales;

    private Integer inventory;

    private Byte status;

    private Integer createTime;

    private Integer updateTime;

    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getGoodsName() {
        return goodsName;
    }


    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }


    public Double getPrice() {
        return price;
    }


    public void setPrice(Double price) {
        this.price = price;
    }


    public String getGoodsDesc() {
        return goodsDesc;
    }


    public void setGoodsDesc(String goodsDesc) {
        this.goodsDesc = goodsDesc;
    }


    public Integer getSales() {
        return sales;
    }


    public void setSales(Integer sales) {
        this.sales = sales;
    }


    public Integer getInventory() {
        return inventory;
    }


    public void setInventory(Integer inventory) {
        this.inventory = inventory;
    }


    public Byte getStatus() {
        return status;
    }


    public void setStatus(Byte status) {
        this.status = status;
    }


    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.create_time
     *
     * @param createTime the value for goods.create_time
     *
     * @mbg.generated Thu Dec 10 15:30:59 CST 2020
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.update_time
     *
     * @return the value of goods.update_time
     *
     * @mbg.generated Thu Dec 10 15:30:59 CST 2020
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.update_time
     *
     * @param updateTime the value for goods.update_time
     *
     * @mbg.generated Thu Dec 10 15:30:59 CST 2020
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }
}